version: 1.0.{build}


install:
  - ps: Install-Product node ''
  - git reset --hard HEAD
  - npm install npm -g
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm run release

test: off